# Generated by Django 4.0.7 on 2022-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
