# Generated by Django 4.0.7 on 2022-09-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(default=None, to='recipes.ingredient'),
        ),
    ]
