# Generated by Django 4.0.7 on 2022-09-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='type',
            new_name='category',
        ),
    ]
